In [25]:
import pandas as pd
import numpy as np
dataset = pd.read_csv("./CreditWorthiness.csv")

In [26]:
print(dataset.info())
print(dataset.describe())
print(dataset.describe(include="O"))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 21 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   Cbal         1000 non-null   object
 1   Cdur         1000 non-null   int64 
 2   Chist        1000 non-null   object
 3   Cpur         1000 non-null   object
 4   Camt         1000 non-null   int64 
 5   Sbal         1000 non-null   object
 6   Edur         1000 non-null   object
 7   InRate       1000 non-null   int64 
 8   MSG          1000 non-null   object
 9   Oparties     1000 non-null   object
 10  Rdur         1000 non-null   object
 11  Prop         1000 non-null   object
 12  age          1000 non-null   int64 
 13  inPlans      1000 non-null   object
 14  Htype        1000 non-null   object
 15  NumCred      1000 non-null   int64 
 16  JobType      1000 non-null   object
 17  Ndepend      1000 non-null   int64 
 18  telephone    1000 non-null   object
 19  foreign      1000 non-null  

In [27]:
sbal = np.unique(dataset['Sbal'])

print(len(sbal), sbal)

5 ['1000 <= Rs. < 5,000' '5000 <= Rs. < 10,000' 'Rs. < 1000' 'Rs. >= 10,000'
 'no savings account']


In [28]:
dues_index = np.where(dataset["Chist"]=='dues not paid earlier')

dues_age = []

for i in dues_index[0]:
    dues_age.append(dataset["age"][i])

print(np.array(dues_age).mean())

38.436860068259385


In [29]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier

In [30]:
# dataset['creditScore']=dataset['creditScore'].map({'bad':0,'good':1})
hot_data = pd.get_dummies(dataset, drop_first=True)

outputs = hot_data["creditScore_good"]

inputs = hot_data.drop("creditScore_good", axis=1)



In [31]:
print(inputs.values)
print(outputs.values)

[[    9 13790     2 ...     0     1     0]
 [   15 15250     4 ...     0     1     0]
 [   36 19410     4 ...     0     1     0]
 ...
 [   36 95540     2 ...     0     0     0]
 [   18 19490     3 ...     0     0     0]
 [   36 62170     4 ...     1     1     0]]
[1 1 0 0 1 1 1 1 0 1 1 1 1 1 0 1 0 1 1 1 0 1 1 1 1 1 1 0 1 0 1 1 0 1 1 0 1
 1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 1 0 1 1 0 1 0 1 0 1 1 1 0 1 1 0 1 0 1 0 1 1
 1 1 1 0 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 0 1 1 0 0
 1 0 1 0 0 1 1 1 1 0 0 0 1 0 1 0 1 0 1 0 0 0 1 0 0 1 0 1 0 1 1 1 0 1 1 1 1
 1 1 1 1 0 0 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 1 0 1 1 1 1 0 0 0 1 1 0 1 0 1 1
 1 1 1 1 0 1 1 0 1 1 1 1 0 1 1 1 1 1 1 1 0 1 1 0 1 1 1 1 0 0 1 1 1 0 1 1 1
 1 1 1 1 1 1 1 0 1 0 1 1 1 0 1 1 1 1 1 0 0 1 0 1 1 0 0 1 1 1 1 0 1 0 1 1 1
 1 0 0 1 1 1 1 1 1 1 1 1 0 0 0 0 0 1 0 1 1 1 1 1 1 1 1 1 1 1 0 1 0 1 0 1 0
 1 0 1 0 1 1 1 1 0 1 1 1 0 1 1 1 1 1 0 0 1 1 0 1 1 0 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 0 1 1 1 0 1 1 0 1 1 1 0 1 1 0 1 0 1 0 1 1 0 1 1 1 

In [32]:
train_in,test_in,train_out,test_out = train_test_split(inputs,outputs,test_size=0.25, random_state=1)

logistic = LogisticRegression()

logistic.fit(train_in,train_out)

prediction = logistic.predict(test_in)

acc=accuracy_score(test_out, prediction)
print(acc)

0.748


In [33]:
scaler = StandardScaler()
inputs = scaler.fit_transform(inputs)

train_in,test_in,train_out,test_out = train_test_split(inputs,outputs,test_size=0.25, random_state=1)

logistic = LogisticRegression()

logistic.fit(train_in,train_out)

prediction = logistic.predict(test_in)

std_acc=accuracy_score(test_out, prediction)
print(std_acc)

0.776


In [34]:
x = (1-std_acc)/(1-acc)
print(1-x)

0.11111111111111116


In [48]:

classifier = KNeighborsClassifier(n_neighbors=30)
classifier.fit(train_in,train_out)
prediction = classifier.predict(test_in)
acc = accuracy_score(test_out, prediction)
print(acc)

0.788
